export enum SwapTrancheStatus {
  ADDRESS_GENERATED = "ADDRESS_GENERATED",
  FUNDING_SUBMITTED = "FUNDING_SUBMITTED",
  FUNDED = "FUNDED",
  QUOTE_RECEIVED = "QUOTE_RECEIVED",
  SWAP_SUBMITTED = "SWAP_SUBMITTED",
  SWAPPED = "SWAPPED",
  DEPOSIT_SUBMITTED = "DEPOSIT_SUBMITTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}
